# Use an empty string if you have multiple domain linking to your website
# This string is used to generate the absolute URL for your assets.
#baseURL = 'https://acpatt.com/'
defaultContentLanguage = 'en'
# Emoji in markdown files
enableEmoji = true
languageCode = 'en-gb'
# Number of blog post per page
paginate = 10
theme = 'pico'
# Title of the website is used for the meta tag title
# and the square icon (not the favicon)
title = 'ACPatt'

[params]
customCSS = [
	"style/style.css",
	"style/theme.sass",
] # Path relative to assets folder
customJS = [] # Path relative to assets folder
# Homepage description
# For blog page description you can overwrite it 
# in the front matter
description = "Personal website for me, Andrew"
email = "andrew@acpatt.com"
favicon = '/favicon.ico'
# Dark mode support
# Supported value are :
# - off
# - always
# If commented the theme will use the browser theme.
darkMode = 'always'

# Social parameters for contact_icons widget
[[params.social]]
alt = "email icon"
icon = "icons/email.svg"
name = "email"
url = "mailto:andrew@acpatt.com"

[[params.social]]
alt = "gitlab icon"
blank = true
icon = "icons/gitlab.svg"
name = "gitlab"
url = "https://gitlab.com/acpatt"

[[params.social]]
alt = "linkedin icon"
blank = true
icon = "icons/linkedin.svg"
name = "twitter"
url = "https://www.linkedin.com/in/andrew-charles-patterson/"


# Navigation bar
[menu]

[[menu.main]]
identifier = "home" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/" 
weight = 10 

[[menu.main]]
identifier = "blog" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/blog/" 
weight = 20 

# [[menu.main]]
# identifier = "work" # identifier is use for translations
# pre = "" # pre is inserted before the translation (icons, image, etc)
# url = "/work/" 
# weight = 30 


[[menu.main]]
identifier = "contact" # identifier is use for translations
pre = "" # pre is inserted before the translation (icons, image, etc)
url = "/contact/" 
weight = 40 

# Syntax highlightning
[markup.highlight]
guessSyntax = true 
lineNumbersInTable = true 
noClasses = false # Set to false to use the Pico default theme.
tabWidth = 2 

[taxonomies]
category = "categories"
tag = "tags"

# Translation
# English, French and Italian are supported but you can contribute
# by adding translation to i18n/ folder.
[languages.en]
contentDir = 'content/en'
languageCode = 'en'
languageName = 'English'
weight = 0

#[languages.fr]
#contentDir = 'content/fr'
#languageCode = 'fr'
#languageName = 'Français'
#weight = 2

# Uncomment the following lines to add an italian translation.
# [languages.it]
# contentDir = 'content/it'
# languageCode = 'it'
# languageName = 'Italiano'
# weight = 3

# Uncomment the following lines to add an spanish translation.
# [languages.es]
# contentDir = 'content/es'
# languageCode = 'es'
# languageName = 'Español'
# weight = 4
